services:
  - docker

language: node_js

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

branches:
  only:
    - master
    - staging

before_install:
- sudo rm /usr/local/bin/docker-compose

install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

script:
  - cd project
  - docker-compose build
  - docker images

#######################################
## begin deploy push to Docker registry
#######################################
after_success:
    - if [[ "$TRAVIS_BRANCH" = master ]]; then
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push jhuopensource/meandemo:mongo
      - docker push jhuopensource/meandemo:express_node
      - docker push jhuopensource/meandemo:nginx_angular_node
      fi
