services:
  - docker

language: node_js

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

branches:
  only:
    - master
    - stage
    - dev

before_install:
- sudo rm /usr/local/bin/docker-compose

install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

script:
  - cd project
  - docker-compose build --no-cache
  - docker images
  - echo "Branch " $TRAVIS_BRANCH " detected." 
  ###############
  ## lint test ##
  ###############
  - docker run -it --rm jhuopensource/meandemo:express_node /usr/src/app/node_modules/.bin/eslint -c ./.eslintrc.js ./app.js --debug

###########################################
## Push Master Builds to Docker Registry ##
###########################################
after_success:
  - if [[ $TRAVIS_BRANCH == master ]]; 
    then printf "Build Success\nInitiating Docker Hub Push\n" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push jhuopensource/meandemo:mongo && docker push jhuopensource/meandemo:express_node && docker push jhuopensource/meandemo:nginx_angular_node;
    else printf "Build Success\nNOT pushing to Docker Hub for " $TRAVIS_BRANCH " build";
    fi
